DerianCordobaPerez/Thesis

- .github/workflows/master.yml
> Creation of the workflows for both projects (Mobile and Web) within the master.yml file which will call the respective test scripts in the first instance, expanding the possibility of various functionalities with the growth of the project.
> feat(Root): Create master.yml workflows

- .github/ISSUE_TEMPLATE/config.yml
> Create config.yml for problem templates dynamically.
> feat(Root): Create config.yml for issue templates

- web/.dockerignore
- web/Dockerfile
- web/docker-compose.dev.yml
- web/docker-compose.prod.yml
- web/docker-compose.yml
- web/next.config.js
- web/package.json
- Division of environments through development and production environment.
- New scripts were generated inside the package.json that will speed up the execution of containers through **docker-compose**
``` json
"dev:up": "docker-compose -f docker-compose.yml -f docker-compose.dev.yml up",
"dev:up-build": "docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build",
"prod:up": "docker-compose -f docker-compose.yml -f docker-compose.prod.yml up"
```
> Feature dockerized web project

- README.md
- web/README.md
- Creation general README,
- Modifcation web README.
> Feature creation readme

- web/.gitignore
- web/jest.config.js
- web/package-lock.json
- web/package.json
- web/tests/index.test.js
- Creation basic jest config.
- Creation basic tests.
- Ignore snapshots files.
- Creation new test scripts.
> Feature creation jest tests

- web/jsconfig.json
- Absolute resolution of directories.
- Custom shortcuts to main directories.
> feat(Web): Create jsconfig.json

- .github/workflows/master.yml
> fix(Root): Change Master to main branch

- web/Dockerfile
- web/package.json
- Removal of the yarn lock file in the copy action inside the Dockerfile.
- Reduction of the dev:up:build command making the dev:up command and additional npm flags.
> Refactor scripts docker compose

- .github/ISSUE_TEMPLATE/config.yml
> refactor(Root): Change URL in config.yml

- web/.husky/pre-commit
- Line count validation for .env files
> Feature env files validation

- web/README.md
> refactor(Web): Changing general information for the web project

- web/prisma/schema.prisma
- Added person model.
- Added Address model.
- Relation between Person and Address model.
- Added Disease, Symptom and Condition model.
- Relation between  Disease, Symptom and Condition model.
> Feature schemas tables prisma

- web/pages/api/phones/[number].js
- web/pages/api/phones/index.js
- web/prisma/schema.prisma
> Feature basic phone api

- .github/CODEOWNERS
> feat(Root): Create CODEOWNERS

- .github/workflows/main.yml
- web/cypress.config.js
- web/cypress/e2e/app.spec.js
- web/cypress/fixtures/example.json
- web/cypress/plugins/index.js
- web/jest.config.js
- web/package-lock.json
- web/package.json
- Added cypress dependencie.
- Create script for cypress tests and e2e tests.
- Added basic cypress config.
- Change master workflow to main.
> Feature cypress tests

- .github/workflows/e2e-tests.yml
- .github/workflows/main.yml
> refactor(Root): Added separate file for 2e2 tests

- .github/workflows/ci.yml
- web/.husky/pre-commit
- web/package-lock.json
- web/package.json
- web/pages/_app.js
- web/pages/api/auth/[...nextauth].js
- web/prisma/migrations/20220612032525_postgres_init/migration.sql
- web/prisma/migrations/20220612034408_postgres_init/migration.sql
- web/prisma/schema.prisma
- Added next auth dependencies.
- Remove env files validation in pre commit using husky.
- Creation of user schemes used in next auth for the Credential provider.
- Added meta (Facebook) and google provider for authentication system.
> Feature next auth provider

- web/.eslintrc.json
- web/hoc/withSession.js
- web/pages/index.js
> refactor(Web): Use HOC for separate logic

- web/.eslintrc.json
- web/hoc/withSession.js
- web/pages/index.js
- web/tests/Contexts/Mock/Auth/session.test.js
> Feature auth session test

- .github/PULL_REQUEST_TEMPLATE.md
Update PR template.
- https://thesis-unan.atlassian.net/browse/MT-5
> refactor: Update pull request template

- .github/workflows/codeql-analysis.yml
- Remove unnecessary events trigger
- [Remove unnecessary events trigger](https://thesis-unan.atlassian.net/browse/MT-6
> refactor(Web): Remove unnecessary events trigger

- .github/workflows/codeql-analysis.yml
- .github/workflows/e2e-tests-web.yml
- .github/workflows/unit-tests-web.yml
- web/pages/api/auth/[...nextauth].js
Fix env variables of Cypress on CI.
- Changed path filter on `pull_request` trigger.
- [MT-7: Fix Env variables of Cypress on CI](https://thesis-unan.atlassian.net/browse/MT-7)
> MT-7: Fix Env variables of Cypress on CI

- .github/CODEOWNERS
- I removed users.
- [MT-23: Update CODEOWNERS file](https://thesis-unan.atlassian.net/browse/MT-23)
> MT-23: Update CODEOWNERS file
